name: Auto Update Proxies and Accounts
on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight <button class="citation-flag" data-index="2"><button class="citation-flag" data-index="10">
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        env:
          CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}  # Reference the secret <button class="citation-flag" data-index="9">
        run: |
          python update_files.py  # Your script to modify proxies.txt and accounts.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update proxies and accounts"
          branch: main
          file_pattern: "proxies.txt,accounts.txt"
